### ISSUE TITLE
git-annex branch wasn't pushed

### ISSUE THREAD

**Issue by yarikoptic** [templateflow/tpl-MNI152NLin2009cAsym#1]
AFAIK `datalad publish` should have pushed it...

**Comment by oesteban** [comment]
I didn't `datalad publish`, so my mistake.

I kind of assumed that will actually upload files to their respective location?

for the case of `tpl-fMRIPrep` I'm aware that it is not in a sane state.

**Comment by oesteban** [comment]
I guess this is not okay... https://github.com/templateflow/tpl-MNI152NLin2009cAsym/compare/git-annex?expand=1

**Comment by yarikoptic** [comment]
> I kind of assumed that will actually upload files to their respective location?
upload files? you mean to github?  it doesn't support "hosting of git-annex'ed files", so no files would be uploaded here. I assume that you added those files to git-annex while pointing urls to OSF, so that is where they would be fetched from by git annex when ppl would clone this repo locally and issue "git annex get" or "datalad get" commands

**Comment by yarikoptic** [comment]
> I guess this is not okay... https://github.com/templateflow/tpl-MNI152NLin2009cAsym/compare/git-annex?expand=1

why do you think so?  just seems to mark existence of a clone ( your local one?) where those files are present

**Comment by oesteban** [comment]
@rciric have we solved this problem with your latest updates?

**Comment by yarikoptic** [comment]
I think so (at least for the latest version of things):
```
hopa:/tmp
$> datalad install -g https://github.com/templateflow/tpl-MNI152NLin2009cAsym
[INFO   ] Cloning https://github.com/templateflow/tpl-MNI152NLin2009cAsym [1 other candidates] into '/tmp/tpl-MNI152NLin2009cAsym' 
[INFO   ]   Remote origin not usable by git-annex; setting annex-ignore          
install(ok): /tmp/tpl-MNI152NLin2009cAsym (dataset)
action summary:                                                                                 
  get (ok: 25)                                                                                   
  install (ok: 1)                                                                                
datalad install -g https://github.com/templateflow/tpl-MNI152NLin2009cAsym  10.07s user 2.27s system 67% cpu 18.202 total  
```
