### ISSUE TITLE
Unable to load template

### ISSUE THREAD

**Issue by RuiHe1999** [templateflow/tpl-MNI152NLin2009cAsym#13]
Hi there,

Thanks for providing this template. I'd like to load it with nib by:

mni152 = nib.load(api.get("MNI152Lin", resolution=2, desc="brain", suffix="mask"))

And it returned: ImageFileError: File C:\Users\.cache\templateflow\tpl-MNI152Lin\tpl-MNI152Lin_res-02_desc-brain_mask.nii.gz is not a gzip file

I checked the file it referred to, and the system said this file might be broken or invalid or something like that. Then I tried to download the templates again using two approaches:

1.  api.get('MNI152NLin2009cAsym')
2. datalad install -g ///templateflow/tpl-MNI152NLin2009cAsym

For the second approach, the files were downloaded directly in the "Users" file folder, so I copied and pasted into the cache folder. 

Unfortunately, neither of them helped solve the problem. The downloaded files are still unloadable. May you please give me some ideas on how to fix such an issue? Many thanks in advance. 

I'm using a windows system for your information. 

Best regards

**Comment by oesteban** [comment]
Hi @RuiHe1999 this looks like a corrupt cache.

You can clear it up with:
```Python
from templateflow import conf
conf.wipe()
```

However, I fear you might have a stale environment, considering you tried the datalad download. Please try the `wipe()` route and let us know what happened.
