### ISSUE TITLE
unable to load templateflow-files

### ISSUE THREAD

**Issue by annikabrueckner** [templateflow/tpl-MNI152NLin2009cAsym#17]
Hey everybody, 

it seems that loading the templateflow-files still is bugging in some way. 
After entering the following code (within conda/terminal as well as in jupyter notebook) the error message below occurs: 

from templateflow import api
api.get('MNI152NLin2009cAsym')

Can you help out?

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-22-8539af0137ef> in <module>
----> 1 from templateflow import api
      2 api.get('MNI152NLin2009cAsym')

~/miniconda3/envs/myenv/lib/python3.6/site-packages/templateflow/__init__.py in <module>
     17 
     18 import os
---> 19 from . import api
     20 from .conf import update, TF_USE_DATALAD
     21 

~/miniconda3/envs/myenv/lib/python3.6/site-packages/templateflow/api.py in <module>
      5 import sys
      6 
----> 7 from .conf import TF_LAYOUT, TF_S3_ROOT, TF_USE_DATALAD, requires_layout
      8 
      9 

~/miniconda3/envs/myenv/lib/python3.6/site-packages/templateflow/conf/__init__.py in <module>
    127 
    128 with suppress(ImportError):
--> 129     init_layout()

~/miniconda3/envs/myenv/lib/python3.6/site-packages/templateflow/conf/__init__.py in init_layout()
    104 
    105 def init_layout():
--> 106     from templateflow.conf.bids import Layout
    107     from bids.layout.index import BIDSLayoutIndexer
    108 

~/miniconda3/envs/myenv/lib/python3.6/site-packages/templateflow/conf/bids.py in <module>
      1 """Extending pyBIDS for querying TemplateFlow."""
      2 from pkg_resources import resource_filename
----> 3 from bids.layout import BIDSLayout, add_config_paths
      4 
      5 add_config_paths(templateflow=resource_filename("templateflow", "conf/config.json"))

~/miniconda3/envs/myenv/lib/python3.6/site-packages/bids/__init__.py in <module>
      1 from .due import due, Doi
----> 2 from .layout import BIDSLayout, BIDSLayoutIndexer
      3 
      4 # For backwards compatibility
      5 from bids_validator import BIDSValidator

~/miniconda3/envs/myenv/lib/python3.6/site-packages/bids/layout/__init__.py in <module>
----> 1 from .layout import BIDSLayout, Query
      2 from .models import (BIDSFile, BIDSImageFile, BIDSDataFile, BIDSJSONFile,
      3                      Config, Entity, Tag)
      4 from .index import BIDSLayoutIndexer
      5 from .utils import add_config_paths, parse_file_entities

~/miniconda3/envs/myenv/lib/python3.6/site-packages/bids/layout/layout.py in <module>
     13 import sqlalchemy as sa
     14 from sqlalchemy.orm import aliased
---> 15 from bids_validator import BIDSValidator
     16 
     17 from ..utils import listify, natural_sort

~/miniconda3/envs/myenv/lib/python3.6/site-packages/bids_validator/__init__.py in <module>
      1 """BIDS validator common Python package."""
----> 2 from .bids_validator import BIDSValidator
      3 __all__ = ['BIDSValidator']
      4 
      5 from . import _version

~/miniconda3/envs/myenv/lib/python3.6/site-packages/bids_validator/bids_validator.py in <module>
      6 
      7 
----> 8 class BIDSValidator():
      9     """Object for BIDS (Brain Imaging Data Structure) verification.
     10 

~/miniconda3/envs/myenv/lib/python3.6/site-packages/bids_validator/bids_validator.py in BIDSValidator()
    122 
    123     @staticmethod
--> 124     @lru_cache
    125     def get_regular_expressions(file_name):
    126         """Read regular expressions from a file."""

~/miniconda3/envs/myenv/lib/python3.6/functools.py in lru_cache(maxsize, typed)
    475     # integer or None.
    476     if maxsize is not None and not isinstance(maxsize, int):
--> 477         raise TypeError('Expected maxsize to be an integer or None')
    478 
    479     def decorating_function(user_function):

TypeError: Expected maxsize to be an integer or None

**Comment by effigies** [comment]
This is https://github.com/bids-standard/pybids/issues/1048. Downgrade `bids-validator<=1.14.0`.

**Comment by annikabrueckner** [comment]
That's awesome! Thanks for providing the hint. It worked! ;)
