### ISSUE TITLE
templates download as empty nifti files

### ISSUE THREAD

**Issue by switt4** [templateflow/tpl-MNI152NLin2009cAsym#7]
Hi,

I posted something similar on the NeuroStars website, but I haven't found any solution yet.  

I am trying to download the MNI152NLin2009cAsym templates via template flow.  I have tried using the python, but the templateflow-skel.zip file just contained empty nifti files (the non-image files were not empty, though).

I stumbled on this thread (https://github.com/templateflow/tpl-MNI152NLin2009cAsym/issues/6) and tried the datalad option for downloading the templates.  

I got this error:
```datalad install -g ///templateflow/tpl-MNI152NLin2009cAsym
[INFO   ] Cloning http://datasets.datalad.org/templateflow/tpl-MNI152NLin2009cAsym [1 other candidates] into '/Users/switt/tpl-MNI152NLin2009cAsym' 
[ERROR  ] Failed to clone from any candidate source URL. Encountered errors per each url were: (OrderedDict([('http://datasets.datalad.org/templateflow/tpl-MNI152NLin2009cAsym', "Cmd('git') failed due to: exit code(128)\n  cmdline: git clone --progress -v http://datasets.datalad.org/templateflow/tpl-MNI152NLin2009cAsym /Users/switt/tpl-MNI152NLin2009cAsym [cmd.py:wait:412]"), ('http://datasets.datalad.org/templateflow/tpl-MNI152NLin2009cAsym/.git', "Cmd('git') failed due to: exit code(128)\n  cmdline: git clone --progress -v http://datasets.datalad.org/templateflow/tpl-MNI152NLin2009cAsym/.git /Users/switt/tpl-MNI152NLin2009cAsym [cmd.py:wait:412]")]),) [install(/Users/switt/tpl-MNI152NLin2009cAsym)] 
install(error): /Users/switt/tpl-MNI152NLin2009cAsym (dataset) [Failed to clone from any candidate source URL. Encountered errors per each url were: (OrderedDict([('http://datasets.datalad.org/templateflow/tpl-MNI152NLin2009cAsym', "Cmd('git') failed due to: exit code(128)\n  cmdline: git clone --progress -v http://datasets.datalad.org/templateflow/tpl-MNI152NLin2009cAsym /Users/switt/tpl-MNI152NLin2009cAsym [cmd.py:wait:412]"), ('http://datasets.datalad.org/templateflow/tpl-MNI152NLin2009cAsym/.git', "Cmd('git') failed due to: exit code(128)\n  cmdline: git clone --progress -v http://datasets.datalad.org/templateflow/tpl-MNI152NLin2009cAsym/.git /Users/switt/tpl-MNI152NLin2009cAsym [cmd.py:wait:412]")]),)]
[WARNING] path not associated with any dataset [get(/Users/switt/tpl-MNI152NLin2009cAsym)] 
action summary:
  get (impossible: 1)
  install (error: 1)
```

I checked on the datalad website, and it looks as if all of the nifti files have been deleted?

<img width="719" alt="Screen Shot 2019-10-07 at 9 54 00 AM" src="https://user-images.githubusercontent.com/39967319/66317943-6ff69b00-e8e8-11e9-89e1-5afca57000af.png">

Is there anyway I can download these templates, or have someone just send me the Harvard Oxford 0thr template in MNI152NLin2009cAsym space?  I would really like to finish up some code before the ISMRM deadline.

Thanks,

suzanne

**Comment by amyh101** [comment]
Hi @oesteban 

I am having the same issue with downloading the MNI152NLin2009cAsym templates. I have attempted to download these files using templateflow and directly through GitHub. While the files do download, the nii's are empty. 

Any advice?

Thanks!!

**Comment by oesteban** [comment]
@amyh101, sorry for the slow response. Did you finally worked this out?

If now, could you check out our documentation first https://www.templateflow.org/ and see whether your particular issue is still missing?

**Comment by oesteban** [comment]
Okay, I actually started an FAQ with this question - https://www.templateflow.org/client/#why-am-i-getting-zero-sized-nifti-files

Please reopen if you keep having issues.

**Comment by NatashaLTaylor** [comment]
Hi,
I am having a similar but slightly different problem specifically with downloading relevant files for tpl-MNI152NLin2009bSym and tpl-MNI152NLin2009bAsym. 
Code as follows through python:
`from templateflow import api as tflow
path = tflow.get("MNI152NLin2009bSym", desc=None, resolution=1, suffix="T1w", extension="nii.gz")
print(path)`
These files are only 353 bytes - and I cannot use them in any other functions, specifically trying to use these as a template for a reference in flirt.
Receive the following error message: 
Image Exception : #22 :: Failed to read volume tpl-MNI152NLin2009bSym_res-1_T1w.nii.gz
Error : Error: file does not appear to be a valid NIFTI or ANALYZE image

I suspect for some reason the  tpl-MNI152NLin2009bSym folder is not properly downloading through templateflow - I've confirmed the other resolutions have downloaded correctly such as tpl-MNI152NLin2009aSym.
Any assistance on this would be greatly appreciated - I'm sure I've just missed something. 

Thanks!
Natasha

<img width="1045" height="61" alt="Image" src="https://github.com/user-attachments/assets/85a9ba2b-f766-49d2-be52-57471877a162" />
